version: '3'
volumes:
  data:
services:
  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: mydealz
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MARIADB_ROOT_PASSWORD: your_root_password
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
  web:
    build: .  
    depends_on:
      - db
    command: /wait-for-it.sh db:3306 -- python main.py